version: "3"

tasks:
  install:ubuntu:common:
    desc: Install common packages for Ubuntu
    cmds:
      - which sudo || apt-get update && apt-get install -y sudo
      - sudo apt-get update
      - sudo apt-get install -y --no-install-recommends \
          build-essential \
          curl \
          wget \
          git \
          unzip \
          jq \
          vim \
          zsh \
          openssh-client \
          tmux \
          file \
          bash-completion \
          dbus \
          dnsutils \
          nano \
          sshpass \
          net-tools \
          tree \
          fzf \
          gron \
          ipcalc \
          lsb-release
          ca-certificates
      - sudo apt-get clean

  install:docker:
    desc: Install Docker
    cmds:
      - curl https://get.docker.com/ | sudo bash
      - sudo usermod -aG docker $USER

  install:ohmyzsh:
    desc: Install Oh My Zsh
    vars:
      CHANGE_SHELL: "{{ default false .CHANGE_SHELL }}"
    cmds:
      - sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      - |
        if [ "{{.CHANGE_SHELL}}" = "true" ]; then
          echo "Changing default shell to zsh"
          chsh -s $(which zsh)
        else
          echo "Skipping changing default shell to zsh"
        fi


  install:aws:
    desc: Install AWS CLI v2
    cmds:
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
      - rm -rf awscliv2.zip aws
      - echo "complete -C '/usr/local/bin/aws_completer' aws" >> ~/.bashrc
      - |
        if [ -f ~/.zshrc ]; then
          echo "complete -C '/usr/local/bin/aws_completer' aws" >> ~/.zshrc
        else
          echo "Zsh configuration file not found, skipping completion setup for Zsh"
        fi
      - mkdir -p ~/.aws
      - touch ~/.aws/credentials
      - touch ~/.aws/config

  install:terraform:
    desc: Install Terraform
    vars:
      TERRAFORM_VERSION: "1.8.3"
    cmds:
      - wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - sudo install terraform /usr/local/bin/
      - rm -rf terraform*.zip terraform
      - echo "complete -C '/usr/local/bin/terraform' terraform" >> ~/.bashrc
      - echo "complete -C '/usr/local/bin/terraform' terraform" >> ~/.zshrc

  install:terragrunt:
    desc: Install Terragrunt
    vars:
      TERRAGRUNT_VERSION: "0.58.8"
    cmds:
      - wget https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_linux_amd64
      - sudo install terragrunt_linux_amd64 /usr/bin/terragrunt
      - rm -rf terragrunt_linux_amd64
      - echo "complete -C '/usr/bin/terragrunt' terragrunt" >> ~/.bashrc
      - echo "complete -C '/usr/bin/terragrunt' terragrunt" >> ~/.zshrc

  install:kubectl:
    desc: Install kubectl
    vars:
      KUBECTL_VERSION: "1.30.0"
    cmds:
      - curl -LO https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl
      - sudo install kubectl /usr/local/bin/
      - rm -rf kubectl

  install:helm:
    desc: Install Helm
    cmds:
      - curl -s https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
